version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=University_P@ssw0rd
      - MSSQL_PID=Developer
    volumes:
      - university_data:/var/opt/mssql
      - ./sql:/usr/src/app/sql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "University_P@ssw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  university_data:
